import product from '@/assets/images/product.png';

export const carts = [
  {
    id: '1',
    name: 'Product 1',
    price: 100,
    quantity: 1,
    category: 'Category 1',
    urlImage: product,
    total: '100.000.000 đ',
  },
  {
    id: '2',
    name: 'Product 2',
    price: 100,
    quantity: 1,
    category: 'Category 1',
    urlImage: product,
    total: '100.000.000 đ',
  },
  {
    id: '3',
    name: 'Product 3',
    price: 100,
    quantity: 1,
    category: 'Category 1',
    urlImage: product,
    total: '100.000.000 đ',
  },
  {
    id: '4',
    name: 'Product 4',
    price: 100,
    quantity: 1,
    category: 'Category 1',
    urlImage: product,
    total: '100.000.000 đ',
  },
  {
    id: '5',
    name: 'Product 5',
    price: 100,
    quantity: 1,
    category: 'Category 1',
    urlImage: product,
    total: '100.000.000 đ',
  },
  {
    id: '6',
    name: 'Product 6',
    price: 100,
    quantity: 1,
    category: 'Category 1',
    urlImage: product,
    total: '100.000.000 đ',
  },
  {
    id: '7',
    name: 'Product 7',
    price: 100,
    quantity: 1,
    category: 'Category 1',
    urlImage: product,
    total: '100.000.000 đ',
  },
  {
    id: '8',
    name: 'Product 8',
    price: 100,
    quantity: 1,
    category: 'Category 1',
    urlImage: product,
    total: '100.000.000 đ',
  },
  {
    id: '9',
    name: 'Product 9',
    price: 100,
    quantity: 1,
    category: 'Category 1',
    urlImage: product,
    total: '100.000.000 đ',
  },
];
